
package Vista;
import Controlador.Controlador_Citas;
import Modelo.Cita;
import Modelo.Pacientes;
import java.awt.Color;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class Pendientes extends javax.swing.JFrame {

    int xMouse,yMouse;
    Color c1 = new Color(145, 196, 207);
    Color c2 = new Color(133, 178, 189);
    Color c3 = new Color(114, 152, 161);
    Color cv1 = new Color(194,218,220);
    Color cv2 = new Color(209,236,239);
    Color cv3 = new Color(168,191,191);
    
    //Ordenar
    TableRowSorter<TableModel> sorter;
    
    //indicar si los botones hacne su función;
    boolean bandera=false;
    
    private int id_cita;
    
    static String titulo[]={"Id Cita","Nombre","Apellido","Celular","Fecha","Hora","Motivo","Nota","Monto","Estado"};
    public static DefaultTableModel modelo= new DefaultTableModel(null,titulo);
    public static Pacientes p_cita = new Pacientes();
    Controlador_Citas con_citas = new Controlador_Citas();
    
    public Pendientes() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        pnlExit = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        pnlAtras = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlCrear = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlEditar = new javax.swing.JPanel();
        lblCambiar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblUsuario3 = new javax.swing.JLabel();
        lblUsuario4 = new javax.swing.JLabel();
        cbDia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        txtAnho = new javax.swing.JTextField();
        cbHora = new javax.swing.JComboBox<>();
        cbMinutos = new javax.swing.JComboBox<>();
        lblUsuario5 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        lblUsuario6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNota = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblUsuario2 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        pnlSeleccionar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnAprobar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(850, 0));

        jPanel1.setBackground(new java.awt.Color(194, 218, 220));
        jPanel1.setPreferredSize(new java.awt.Dimension(919, 795));

        pnlHeader.setBackground(new java.awt.Color(194, 218, 220));
        pnlHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlHeaderMouseDragged(evt);
            }
        });
        pnlHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHeaderMousePressed(evt);
            }
        });

        pnlExit.setBackground(new java.awt.Color(194, 218, 220));

        lblCerrar.setBackground(new java.awt.Color(255, 255, 255));
        lblCerrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(0, 0, 0));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setText("X");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlExitLayout = new javax.swing.GroupLayout(pnlExit);
        pnlExit.setLayout(pnlExitLayout);
        pnlExitLayout.setHorizontalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        pnlExitLayout.setVerticalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnlAtras.setBackground(new java.awt.Color(194, 218, 220));
        pnlAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAtrasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlAtrasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlAtrasMouseReleased(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back.png"))); // NOI18N

        javax.swing.GroupLayout pnlAtrasLayout = new javax.swing.GroupLayout(pnlAtras);
        pnlAtras.setLayout(pnlAtrasLayout);
        pnlAtrasLayout.setHorizontalGroup(
            pnlAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );
        pnlAtrasLayout.setVerticalGroup(
            pnlAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addComponent(pnlAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlCrear.setBackground(new java.awt.Color(133, 178, 189));
        pnlCrear.setForeground(new java.awt.Color(255, 255, 255));
        pnlCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCrearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCrearMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlCrearMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlCrearMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CREAR CITA");

        javax.swing.GroupLayout pnlCrearLayout = new javax.swing.GroupLayout(pnlCrear);
        pnlCrear.setLayout(pnlCrearLayout);
        pnlCrearLayout.setHorizontalGroup(
            pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );
        pnlCrearLayout.setVerticalGroup(
            pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlEditar.setBackground(new java.awt.Color(133, 178, 189));
        pnlEditar.setForeground(new java.awt.Color(255, 255, 255));
        pnlEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlEditarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlEditarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlEditarMouseReleased(evt);
            }
        });

        lblCambiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCambiar.setForeground(new java.awt.Color(255, 255, 255));
        lblCambiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCambiar.setText("CAMBIAR CITA");

        javax.swing.GroupLayout pnlEditarLayout = new javax.swing.GroupLayout(pnlEditar);
        pnlEditar.setLayout(pnlEditarLayout);
        pnlEditarLayout.setHorizontalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCambiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );
        pnlEditarLayout.setVerticalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCambiar)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(194, 218, 220));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cita", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        lblUsuario3.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario3.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario3.setText("Fecha:");

        lblUsuario4.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario4.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario4.setText("Hora:");

        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        txtAnho.setBackground(new java.awt.Color(194, 218, 220));
        txtAnho.setForeground(new java.awt.Color(0, 0, 0));
        txtAnho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnhoActionPerformed(evt);
            }
        });

        cbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        cbMinutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));

        lblUsuario5.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario5.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario5.setText("Motivo:");

        txtMotivo.setBackground(new java.awt.Color(194, 218, 220));
        txtMotivo.setForeground(new java.awt.Color(0, 0, 0));
        txtMotivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblUsuario6.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario6.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario6.setText("Nota");

        txtNota.setBackground(new java.awt.Color(194, 218, 220));
        txtNota.setColumns(20);
        txtNota.setForeground(new java.awt.Color(0, 0, 0));
        txtNota.setRows(5);
        txtNota.setText(" ");
        jScrollPane2.setViewportView(txtNota);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Monto:");

        txtMonto.setBackground(new java.awt.Color(194, 218, 220));
        txtMonto.setForeground(new java.awt.Color(0, 0, 0));
        txtMonto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblUsuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnho, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(lblUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMotivo)))
                    .addComponent(jScrollPane2)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario3)
                    .addComponent(jLabel1)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario4)
                    .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario5)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblUsuario6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(194, 218, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paciente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        txtNombre.setBackground(new java.awt.Color(194, 218, 220));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtNombre.setEnabled(false);

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Nombre");

        lblUsuario1.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario1.setText("Apellido");

        txtApellido.setBackground(new java.awt.Color(194, 218, 220));
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtApellido.setEnabled(false);

        lblUsuario2.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario2.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario2.setText("Numero");

        txtNumero.setBackground(new java.awt.Color(194, 218, 220));
        txtNumero.setForeground(new java.awt.Color(0, 0, 0));
        txtNumero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtNumero.setEnabled(false);

        pnlSeleccionar.setBackground(new java.awt.Color(133, 178, 189));
        pnlSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        pnlSeleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSeleccionarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSeleccionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSeleccionarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlSeleccionarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlSeleccionarMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SELECCIONAR");

        javax.swing.GroupLayout pnlSeleccionarLayout = new javax.swing.GroupLayout(pnlSeleccionar);
        pnlSeleccionar.setLayout(pnlSeleccionarLayout);
        pnlSeleccionarLayout.setHorizontalGroup(
            pnlSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );
        pnlSeleccionarLayout.setVerticalGroup(
            pnlSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSeleccionarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario1)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario2)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblUsuario2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblUsuario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario)
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "Numero", "Fecha", "Hora", "Motivo", "Nota", "Monto", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setModel(modelo);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabla.getColumnModel().getColumn(4).setPreferredWidth(60);
            tabla.getColumnModel().getColumn(5).setPreferredWidth(30);
            tabla.getColumnModel().getColumn(8).setPreferredWidth(50);
        }

        btnAprobar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eliminar.png"))); // NOI18N
        btnAprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprobarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Aprobar.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(pnlCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(pnlEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAprobar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnAprobar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addContainerGap(87, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        pnlExit.setBackground(Color.RED);
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        Color c = new Color(194,218,220);
        pnlExit.setBackground(c);
    }//GEN-LAST:event_lblCerrarMouseExited

    private void pnlHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_pnlHeaderMouseDragged

    private void pnlHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlHeaderMousePressed

    private void txtAnhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnhoActionPerformed

    private void pnlCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCrearMouseClicked
        if(EstaVacio()==true){
            JOptionPane.showMessageDialog(null,"Existe un campo de cita vacio, hagalo denuevo");
        }
        else{
            Cita c = new Cita();
            int id_nuevaCita;


            //Darle un id a la cita
            try {
                List<Cita> c_total = con_citas.leerCitas();
                if(c_total.isEmpty()){
                    c.setId_cita(1);
                } else {
                    id_nuevaCita = c_total.get(c_total.size()-1).getId_cita()+1;
                    c.setId_cita(id_nuevaCita);
                }     
            } catch (IOException ex) {
                System.err.println("Error: "+ex);
            }

            //darle formato a la fecha 
            if(cbMes.getSelectedIndex()<9){
                if(txtAnho.getText().equals(""))
                    c.setFecha(cbDia.getSelectedItem().toString() + "-0" + (cbMes.getSelectedIndex()+1) + "-" + "0000");
                else
                    c.setFecha(cbDia.getSelectedItem().toString() + "-0" + (cbMes.getSelectedIndex()+1) + "-" + txtAnho.getText());

            } else{
                if(txtAnho.getText().equals(""))
                    c.setFecha(cbDia.getSelectedItem().toString() + "-" + (cbMes.getSelectedIndex()+1) + "-" + "0000");
                else
                    c.setFecha(cbDia.getSelectedItem().toString() + "-" + (cbMes.getSelectedIndex()+1) + "-" + txtAnho.getText());
            }


            c.setId_paciente(Integer.parseInt(lblId.getText()));
            c.setHora(cbHora.getSelectedItem().toString() + ":" + cbMinutos.getSelectedItem());
            c.setMotivo(txtMotivo.getText());
            c.setNota(txtNota.getText());
            c.setMonto(txtMonto.getText());
            c.setEstado("Pendiente");


            try {
                con_citas.CrearCitas(c);
                con_citas.LlenarTabla_Pendientes();
            } catch (IOException ex) {
                System.err.println("Error: "+ex);
            }

            Hora();
            Limpiar();
            BloquearBotones(true);
        }
        
    }//GEN-LAST:event_pnlCrearMouseClicked

    private void pnlCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCrearMouseEntered
        pnlCrear.setBackground(c1);
    }//GEN-LAST:event_pnlCrearMouseEntered

    private void pnlCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCrearMouseExited
        pnlCrear.setBackground(c2);

    }//GEN-LAST:event_pnlCrearMouseExited

    private void pnlCrearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCrearMousePressed
        pnlCrear.setBackground(c3);
    }//GEN-LAST:event_pnlCrearMousePressed

    private void pnlCrearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCrearMouseReleased

        pnlCrear.setBackground(c2);
    }//GEN-LAST:event_pnlCrearMouseReleased

    private void pnlEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditarMouseClicked
        
        //Verificar si está vacio
        if(EstaVacio()==true){
            JOptionPane.showMessageDialog(null,"Un campo dela cita está vacío, hagalo denuevo");
        } else {
            Cita c = new Cita();
            
            //Verificar si selecciono una cita
            if(id_cita==0){
                JOptionPane.showMessageDialog(null,"No selecciono una cita, hagalo denuevo");
            } else {
                c.setId_cita(id_cita);


            //darle formato a la fecha 
                if(cbMes.getSelectedIndex()<9){
                    if(txtAnho.getText().equals(""))
                        c.setFecha(cbDia.getSelectedItem().toString() + "-0" + (cbMes.getSelectedIndex()+1) + "-" + "0000");
                    else
                        c.setFecha(cbDia.getSelectedItem().toString() + "-0" + (cbMes.getSelectedIndex()+1) + "-" + txtAnho.getText());

                } else{
                    if(txtAnho.getText().equals(""))
                        c.setFecha(cbDia.getSelectedItem().toString() + "-" + (cbMes.getSelectedIndex()+1) + "-" + "0000");
                    else
                        c.setFecha(cbDia.getSelectedItem().toString() + "-" + (cbMes.getSelectedIndex()+1) + "-" + txtAnho.getText());
                }
                
                c.setId_paciente(Integer.parseInt(lblId.getText()));
                c.setHora(cbHora.getSelectedItem().toString() + ":" + cbMinutos.getSelectedItem());
                c.setMotivo(txtMotivo.getText());
                c.setEstado("Pendiente");
                c.setNota(txtNota.getText());
                c.setMonto(txtMonto.getText());

            }
            try {
                con_citas.actualizarCita(c);
                con_citas.LlenarTabla_Pendientes();
            } catch (IOException ex) {
                System.err.println("Error: "+ex);
            }
            Hora();
            Limpiar();
            BloquearBotones(true);
        }
    }//GEN-LAST:event_pnlEditarMouseClicked

    private void pnlEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditarMouseEntered
        pnlEditar.setBackground(c1);
    }//GEN-LAST:event_pnlEditarMouseEntered

    private void pnlEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditarMouseExited
        pnlEditar.setBackground(c2);
    }//GEN-LAST:event_pnlEditarMouseExited

    private void pnlEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditarMousePressed
        pnlEditar.setBackground(c3);
    }//GEN-LAST:event_pnlEditarMousePressed

    private void pnlEditarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditarMouseReleased
        pnlEditar.setBackground(c2);
    }//GEN-LAST:event_pnlEditarMouseReleased

    private void pnlSeleccionarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSeleccionarMouseReleased
        pnlSeleccionar.setBackground(c2);
    }//GEN-LAST:event_pnlSeleccionarMouseReleased

    private void pnlSeleccionarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSeleccionarMousePressed
        pnlSeleccionar.setBackground(c3);
    }//GEN-LAST:event_pnlSeleccionarMousePressed

    private void pnlSeleccionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSeleccionarMouseExited
        pnlSeleccionar.setBackground(c2);
    }//GEN-LAST:event_pnlSeleccionarMouseExited

    private void pnlSeleccionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSeleccionarMouseEntered
         pnlSeleccionar.setBackground(c1);
    }//GEN-LAST:event_pnlSeleccionarMouseEntered

    private void pnlSeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSeleccionarMouseClicked
        try {
            Lista_Pacientes li = new Lista_Pacientes();
            li.setVisible(true);
            li.enviar=1;
        } catch (IOException ex) {
            System.err.println("Error: "+ex);
        }
        
    }//GEN-LAST:event_pnlSeleccionarMouseClicked

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int fila=tabla.getSelectedRow();
        id_cita = Integer.parseInt(tabla.getValueAt(fila,0).toString());
        
        try {
            lblId.setText(con_citas.buscarCita(id_cita).getId_paciente()+"");
        } catch (IOException ex) {
            System.err.println("Error: "+ex);
        }
        
        BloquearBotones(false);
        
        txtNombre.setText(tabla.getValueAt(fila,1).toString());
        txtApellido.setText(tabla.getValueAt(fila,2).toString());
        txtNumero.setText(tabla.getValueAt(fila,3).toString());
        txtMotivo.setText(tabla.getValueAt(fila, 6).toString());
        txtNota.setText(tabla.getValueAt(fila,7).toString());
        txtMonto.setText(tabla.getValueAt(fila,8).toString());
        
        //Separar Fecha
        String[] Fecha = tabla.getValueAt(fila,4).toString().split("-");
        cbDia.setSelectedItem(Fecha[0]);
        cbMes.setSelectedIndex(Integer.parseInt(Fecha[1])-1);
        txtAnho.setText(Fecha[2]);
        //Separar Hora
        String[] Hora = tabla.getValueAt(fila,5).toString().split(":");
        cbHora.setSelectedItem(Hora[0]);
        cbMinutos.setSelectedItem(Hora[1]);  

    }//GEN-LAST:event_tablaMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(id_cita==0){
            JOptionPane.showMessageDialog(null,"No selecciono una cita, hagalo denuevo");
        } else {
            try {
                con_citas.BorrarId(id_cita);
                con_citas.LlenarTabla_Pendientes();
            } catch (IOException ex) {
                System.err.println("Error: "+ex);
            }
        }
        Hora();
        Limpiar();
        BloquearBotones(true);
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprobarActionPerformed
        if(id_cita==0){
            JOptionPane.showMessageDialog(null,"No selecciono una cita, hagalo denuevo");
        } else {
            Cita c = new Cita();
            c.setId_cita(id_cita);
            //si el año está vacio
            if(txtAnho.getText().equals(""))
                c.setFecha(cbDia.getSelectedItem().toString() + "-" + cbMes.getSelectedIndex()+1 + "-" + "0000");
            else
                c.setFecha(cbDia.getSelectedItem().toString() + "-" + cbMes.getSelectedIndex()+1 + "-" + txtAnho.getText());

            c.setId_paciente(Integer.parseInt(lblId.getText()));
            c.setHora(cbHora.getSelectedItem().toString() + ":" + cbMinutos.getSelectedItem());
            c.setMotivo(txtMotivo.getText());
            c.setNota(txtNota.getText());
            c.setMonto(txtMonto.getText());
            c.setEstado("Atendido");

        }
        
        try {
            con_citas.LlenarTabla_Pendientes();
        } catch (IOException ex) {
            System.err.println("Error: "+ex);
        }
        Hora();
        Limpiar();
        BloquearBotones(true);
    }//GEN-LAST:event_btnAprobarActionPerformed

    private void pnlAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAtrasMouseClicked
        Opcion ven = new Opcion();
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlAtrasMouseClicked

    private void pnlAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAtrasMouseEntered
        pnlAtras.setBackground(cv2);
    }//GEN-LAST:event_pnlAtrasMouseEntered

    private void pnlAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAtrasMouseExited
        pnlAtras.setBackground(cv1);
    }//GEN-LAST:event_pnlAtrasMouseExited

    private void pnlAtrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAtrasMousePressed
        pnlAtras.setBackground(cv3);
    }//GEN-LAST:event_pnlAtrasMousePressed

    private void pnlAtrasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAtrasMouseReleased
        pnlAtras.setBackground(cv2);
    }//GEN-LAST:event_pnlAtrasMouseReleased

    public void Hora(){
        LocalDateTime hora = LocalDateTime.now();
        
        DateTimeFormatter formatoDia = DateTimeFormatter.ofPattern("dd");
        DateTimeFormatter formatoMes = DateTimeFormatter.ofPattern("MM");
        DateTimeFormatter formatoAnho = DateTimeFormatter.ofPattern("yyyy");
        DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH");
        DateTimeFormatter formatoMinuto = DateTimeFormatter.ofPattern("mm");
        
        String dia = hora.format(formatoDia);
        String mes = hora.format(formatoMes);
        String anho = hora.format(formatoAnho);
        String horas = hora.format(formatoHora);
        String minuto = hora.format(formatoMinuto);
        
        cbMinutos.setSelectedItem(minuto);
        cbHora.setSelectedItem(horas);
        cbDia.setSelectedItem(dia);
        cbMes.setSelectedItem(mes);
        txtAnho.setText(anho);
    }
    
    public void Limpiar(){
        txtNombre.setText("");
        txtApellido.setText("");
        txtNumero.setText("");
        BloquearBotones(true);
        Hora();
        txtMonto.setText("");
        txtMotivo.setText("");
        txtNota.setText("");
    }
    
    //si deseas bloquear botones (true) | no deseas bloquear botones (false)
    public void BloquearBotones(boolean b){
        if(b==true){
            btnAprobar.setEnabled(false);
            btnEliminar.setEnabled(false);
        }else{
            btnAprobar.setEnabled(true);
            btnEliminar.setEnabled(true);
        }
    }
    public boolean EstaVacio(){
        
        if(txtMonto.getText().equals("") || txtNota.getText().equals("") || txtMotivo.getText().equals("") || txtAnho.getText().equals(""))
            return true;
        else
            return false;
    }
    
    public void Iniciar() throws IOException{
        con_citas.LlenarTabla_Pendientes();
        Hora();
        BloquearBotones(true);
        
        //Ordenar el ID por numero:
        sorter = new TableRowSorter<>(modelo);
            sorter.setComparator(0, new Comparator<Integer>() {
                @Override
                public int compare(Integer o1, Integer o2) {
                    return Integer.compare(o1, o2);
                }
            });
            
         // Comparador para ordenar la columna "Fecha" como fechas
        sorter.setComparator(4, new Comparator<String>() {
            private final SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");

            @Override
            public int compare(String date1, String date2) {
                try {
                    Date d1 = dateFormat.parse(date1);
                    Date d2 = dateFormat.parse(date2);
                    return d1.compareTo(d2);
                } catch (ParseException e) {
                    throw new IllegalArgumentException(e);
                }
            }
        });
        
        tabla.setRowSorter(sorter);
        //tabla.setAutoCreateRowSorter(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pendientes().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Pendientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprobar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbHora;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbMinutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCambiar;
    private javax.swing.JLabel lblCerrar;
    public static javax.swing.JLabel lblId;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JLabel lblUsuario3;
    private javax.swing.JLabel lblUsuario4;
    private javax.swing.JLabel lblUsuario5;
    private javax.swing.JLabel lblUsuario6;
    private javax.swing.JPanel pnlAtras;
    private javax.swing.JPanel pnlCrear;
    private javax.swing.JPanel pnlEditar;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlSeleccionar;
    public javax.swing.JTable tabla;
    private javax.swing.JTextField txtAnho;
    public static javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtMotivo;
    public static javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtNota;
    public static javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
